dist: xenial  # required for Python >= 3.7
language: python
python:
  - 3.7

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install  

script:
  - poetry run mkdocs build --verbose --clean --strict

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  keep_history: true
  skip_cleanup: true
  fqdn: sp3.dev
  local_dir: site
  target_branch: master
  on:
    branch: source
