language: python
python:
  - 3.7-dev
script:
  - mkdocs build --verbose --clean --strict
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: site
  target-branch: master
  on:
    branch: source
  fqdn: sp3.dev
