site_name: SPEG03
site_description: speg03 portal site
site_author: Takahiro Yano
site_url: https://sp3.dev

copyright: Copyright &copy; 2018-2020 Takahiro Yano
google_analytics: [UA-121673953-1, sp3.dev]

theme:
  name: material
  language: ja

extra:
  social:
    - type: github
      link: https://github.com/speg03
    - type: twitter
      link: https://twitter.com/speg03
    - type: facebook-square
      link: https://www.facebook.com/speg03
    - type: envelope-o
      link: mailto:speg03@gmail.com

markdown_extensions:
  - codehilite
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
