site_name: SPEG03
site_description: speg03 portal site
site_author: Takahiro Yano
site_url: https://sp3.dev

copyright: Copyright &copy; 2018-2020 Takahiro Yano

theme:
  name: material
  language: ja

nav:
  - index.md
  - about.md
  - experiences.md
  - products.md
  - activities.md
  - メモ:
    - memo/commands.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/speg03
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/speg03
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/speg03
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/speg03
    - icon: fontawesome/solid/envelope
      link: mailto:speg03@gmail.com

markdown_extensions:
  - codehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
