site_name: speg03 portal
site_description: Portal site about speg03
site_author: Takahiro Yano
site_url: https://speg03.github.io/portal

copyright: Copyright &copy; 2018 Takahiro Yano

theme:
  name: material
  language: ja

pages:
  - Home: index.md

extra:
  social:
    - type: github
      link: https://github.com/speg03
    - type: twitter
      link: https://twitter.com/speg03
    - type: facebook-square
      link: https://www.facebook.com/speg03
    - type: envelope-o
      link: mailto:speg03@gmail.com

markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
