site_name: SP3.dev
site_description: speg03 portal site
site_author: Takahiro Yano
site_url: https://sp3.dev

copyright: Copyright &copy; 2018-2025 Takahiro Yano

theme:
  name: material
  language: ja

nav:
  - index.md
  - about.md
  - experiences.md
  - products.md
  - activities.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/speg03
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/speg03
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/speg03
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/speg03
    - icon: fontawesome/solid/envelope
      link: mailto:speg03@gmail.com

markdown_extensions:
  - codehilite
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tilde
