name: Deploy GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: python3 -m pip install -r requirements.txt

    - name: Build
      run: mkdocs build --verbose --strict

    - name: Deploy GitHub Pages site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        cname: www.sp3.dev
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com
