name: deploy-gh-pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pypoetry
        key: poetry-${{ hashFiles('poetry.lock') }}

    - name: Install poetry
      run: |
        curl -sSLO https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
        python3 ./get-poetry.py --yes
        echo '::add-path::~/.poetry/bin'

    - name: Install dependencies
      run: poetry install

    - name: Build
      run: |
        poetry run mkdocs build --verbose --clean --strict
        cp ./CNAME ./site/

    - uses: actions/upload-artifact@v1
      with:
        name: site
        path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: site

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
