name: Deploy GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
    - uses: dschep/install-poetry-action@v1.3

    - name: Install dependencies
      run: poetry install

    - name: Build
      run: mkdocs build --verbose --strict

    - name: Deploy GitHub Pages site
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
      with:
        username: github-actions[bot]
        useremail: 41898282+github-actions[bot]@users.noreply.github.com
