name: Publish Docs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Build
        run: mkdocs build --verbose --strict

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: www.sp3.dev
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
